[book]
authors = ["ld3zian"]
language = "en"
multilingual = false
src = "src"
title = "ld3z's Site"

[output.html]
git-repository-url = "https://github.com/ld3z/site"
git-repository-icon = "fa-github"
